In [2]:
import pandas as pd
import statsmodels.formula.api as sm

In [3]:
Facebook = pd.read_csv('https://raw.githubusercontent.com/TomdeFluiter/StudentsPerformance/refs/heads/main/Facebook.csv')
Facebook.head()

,Page_total_likes,Type,Post_Month,Post_Weekday,Post_Hour,Payment,Lifetime_Post_Total_Reach,Lifetime_Post_Total_Impressions,Lifetime_Engaged_Users,Lifetime_Post_Consumers,Lifetime_Post_Consumptions,Lifetime_Post_Impressions_by_people_who_have_liked_your_Page,Lifetime_Post_reach_by_people_who_like_your_Page,Lifetime_People_who_have_liked_your_Page_and_engaged_with_your_post,comment,like,share,Total_Interactions
0,139441,Photo,12,4,3,Not_Paid,2752,5091,178,109,159,3078,1640,119,4,79,17,100
1,139441,Status,12,3,10,Not_Paid,10460,19057,1457,1361,1674,11710,6112,1108,5,130,29,164
2,139441,Photo,12,3,3,Not_Paid,2413,4373,177,113,154,2812,1503,132,0,66,14,80
3,139441,Photo,12,2,10,Paid,50128,87991,2211,790,1119,61027,32048,1386,58,1572,147,1777
4,139441,Photo,12,2,3,Not_Paid,7244,13594,671,410,580,6228,3200,396,19,325,49,393

In [6]:
#recode
Facebook_dummies = pd.get_dummies(Facebook['Payment'])
Facebook2 = pd.concat([Facebook,Facebook_dummies], axis=1)
Facebook2.head()

model1 = sm.ols('like~Paid+Not_Paid', data=Facebook2).fit()
print(model1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   like   R-squared:                       0.012
Model:                            OLS   Adj. R-squared:                  0.008
Method:                 Least Squares   F-statistic:                     2.925
Date:                Thu, 26 Sep 2024   Prob (F-statistic):             0.0546
Time:                        11:42:36   Log-Likelihood:                -3561.0
No. Observations:                 495   AIC:                             7128.
Df Residuals:                     492   BIC:                             7141.
Df Model:                           2
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept        -1.537e+15   6.03e+15     -0.255      0.799   -1.34e+16    1.03e+16
Paid[T.True]      1.537e+15   6.03e+15      0.255      0.799   -1.03e+16    1.34e+16
Not_Paid[T.True]  1.537e+15   6.03e+15      0.255      0.799   -1.03e+16    1.34e+16
==============================================================================
Omnibus:                      779.772   Durbin-Watson:                   2.044
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           279150.649
Skew:                           8.792   Prob(JB):                         0.00
Kurtosis:                     118.002   Cond. No.                     9.18e+14
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 9.57e-28. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.